
#ifndef INC_LIB_MTI_EMV_API_H_
#define INC_LIB_MTI_EMV_API_H_

#include "libMtiCommonApi.h"

#ifdef __INGENICO_SRC__
#include "sdk.h"
#include "TlvTree.h"
#include "GTL_Assert.h"
#include "EmvLib_Tags.h"

#include "EPSTOOL_Convert.h"
#include "EPSTOOL_TlvTree.h"

#include "EMV_Status.h"
#include "EMV_ApiTags.h"
#include "EMV_Api.h"

#include "APEMV_ServicesManager.h"
#include "APEMV_ServicesEmv.h"
#include "APEMV_ServicesEmv_0_AppSel.h"
#include "APEMV_ServicesEmv_1_FinalSelect.h"
#include "APEMV_ServicesEmv_2_Init.h"
#include "APEMV_ServicesEmv_3_CVM.h"
#include "APEMV_ServicesEmv_4_ActionAnalysis.h"
#include "APEMV_ServicesEmv_5_OnlineProcessing.h"
#include "APEMV_ServicesEmv_6_Stop.h"
#elif (defined __VERIFONE_SRC__)
#include <svc.h>
#include <svc_sec.h>
#include "tec/tec.h"
#include <svc_sec.h>
#include <EMV/EMV_CT_Interface.h>
#include <EMV/EMV_Common_Interface.h>
#include <emv/E2E_EMV_CTLS_Serialize.h>
#include <emv/EMV_CTLS_Interface.h>
#include <EMV/E2E_EMV_CT_Serialize.h>
#include <emv/btlv.h>

#endif

#define MAX_ACQUIER_BRAND_COUNT							5

#define MTI_EMV_STEP_AID_SELECTION						1
#define MTI_EMV_STEP_INPUT_AMOUNT						2
#define MTI_EMV_STEP_REQ_ONLINE_PIN						3
#define MTI_EMV_STEP_REQ_OFFLINE_PIN					4
#define MTI_EMV_STEP_REQ_DCC							5
#define MTI_EMV_STEP_ARQC_GO_ONLINE						6

#define MTI_EMV_STEP_INIT_PARAM							100
#define MTI_EMV_STEP_PLEASE_WAIT						101
#define MTI_EMV_STEP_WRONG_PIN							102
#define MTI_EMV_STEP_LAST_ATTEMP_PIN					103
#define MTI_EMV_STEP_CORRECT_PIN						104
#define MTI_EMV_STEP_NEED_PIN							105
#define MTI_EMV_STEP_NEED_SIGN							106
#define MTI_EMV_STEP_NEED_AMOUNT						107
#define MTI_EMV_STEP_SELECT_AID							108
#define MTI_EMV_STEP_SELECT_TRAN_TYPE					109
#define MTI_EMV_STEP_NEED_ONLINE						110
#define MTI_EMV_STEP_CONFIRM_PAN						111
#define MTI_EMV_STEP_FORCE_APPROVAL						112
#define MTI_EMV_STEP_OFFLINE_PIN_INPUT					113
#define MTI_EMV_STEP_SHOW_MESSAGE						114
#define MTI_EMV_STEP_TAP_COLLISION						115
#define MTI_EMV_STEP_TRY_CONFIRMATION_CODE_VERFIED		116
#define MTI_EMV_STEP_NEED_PIN_FLAG						117
#define MTI_EMV_STEP_BEFORE_OFFLINE_PIN_INPUT			118

#define MTI_EMV_TRAN_VOID								1000
#define MTI_EMV_TRAN_SALE								1001
#define MTI_EMV_TRAN_DEBIT								1002
#define MTI_EMV_TRAN_REFUND								1003

#define MTI_EMV_TR_SUCCESS								2000
#define MTI_EMV_TR_CANCEL								2001
#define MTI_EMV_TR_CARD_PROCESSING_ERROR				2002
#define MTI_EMV_TR_DECLINED								2003
#define MTI_EMV_TR_SERVICE_NOT_ALLOWED					2004
#define MTI_EMV_TR_CARD_DATA_ERROR						2005
#define MTI_EMV_TR_CANCELLED							2006
#define MTI_EMV_TR_CARD_BLOCKED							2007
#define MTI_EMV_TR_CARD_REMOVED							2008
#define MTI_EMV_TR_CARD_ERROR							2009
#define MTI_EMV_TR_TERMINAL_ERROR						2010
#define MTI_EMV_TR_AID_SELECT_ERROR						2011
#define MTI_EMV_TR_INVALID_CARD							2012
#define MTI_EMV_TR_UNKNOWN_ERROR						2013
#define MTI_EMV_TR_FALLBACK								2014
#define MTI_EMV_TR_OFL_SUCCESS							2015
#define MTI_EMV_TR_APP_BLOCKED							2016
#define MTI_EMV_TR_CARD_AAC								2017
#define MTI_EMV_TR_2CARD_TAP_ERR						2018
#define MTI_EMV_TR_TRY_IC_TRAN							2019
#define MTI_EMV_TR_TRY_INSERT_CARD						2020 //@@WAY PARAM PAYPASS 20210127  

#define MTI_EMV_ONLINE_APPROVED							3000
#define MTI_EMV_ONLINE_DENIAL							3001
#define MTI_EMV_ONLINE_SUSPEND							3002

#define MTI_EMV_RTN_CONTINUE							1
#define MTI_EMV_RTN_SUSPEND								2
#define MTI_EMV_RTN_PIN_BYPASS							3
#define MTI_EMV_TRN_SIGN								4
#define MTI_EMV_TRN_PIN									5


#define	MTI_EMV_TAG_INT_CAPK_EXPONENT						0x9F918703
#define	MTI_EMV_TAG_INT_CAPK_MODULUS						0x9F918704
#define	MTI_EMV_TAG_INT_DEFAULT_DDOL						0x9F918705
#define	MTI_EMV_TAG_INT_DEFAULT_TDOL						0x9F918706
#define	MTI_EMV_TAG_INT_MAX_TARGET_PERC_BIASED_RAND_SEL		0x9F918707
#define	MTI_EMV_TAG_INT_TARGET_PERC_RAND_SEL				0x9F918708
#define	MTI_EMV_TAG_INT_TAC_DEFAULT							0x9F918709
#define MTI_EMV_TAG_INT_AUTHORISATION_RESPONSE_CRYPTOGRAM	0x9F918710
#define	MTI_EMV_TAG_INT_TAC_DENIAL							0x9F91870A
#define	MTI_EMV_TAG_INT_TAC_ONLINE							0x9F91870B
#define	MTI_EMV_TAG_INT_THRESHOLD_VALUE_BIASED_RAND_SEL		0x9F91870C
#define	MTI_EMV_TAG_INT_TRANSACTION_REF_CURRENCY_CONV		0x9F91870D
#define MTI_EMV_TAG_INT_CURRENCY_CODE						0x9F920001
#define MTI_EMV_TAG_INT_NEED_SIGNATURE						0x9F9F0001

enum eEMVStandardTag {
	MTI_EMV_TAG_AID_CARD = 0x4F,
	MTI_EMV_TAG_APPLICATION_LABEL = 0x50,
	MTI_EMV_TAG_TRACK_2_EQU_DATA = 0x57,
	MTI_EMV_TAG_APPLI_PAN = 0x5A,
	MTI_EMV_TAG_APPLI_TEMPLATE = 0x61,
	MTI_EMV_TAG_FCI_TEMPLATE = 0x6F,
	MTI_EMV_TAG_READ_RECORD_RESP_MESSAGE = 0x70,
	MTI_EMV_TAG_ISSUER_SCRIPT_TEMPLATE_1 = 0x71,
	MTI_EMV_TAG_ISSUER_SCRIPT_TEMPLATE_2 = 0x72,
	MTI_EMV_TAG_DICTIONARY_DISCR_TEMPLATE = 0x73,
	MTI_EMV_TAG_RESPONSE_MESSAGE_TEMPLATE_FORMAT_2 = 0x77,
	MTI_EMV_TAG_RESPONSE_MESSAGE_TEMPLATE_FORMAT_1 = 0x80,
	MTI_EMV_TAG_AMOUNT_AUTH_BIN = 0x81,
	MTI_EMV_TAG_AIP = 0x82,
	MTI_EMV_TAG_COMMAND_TEMPLATE = 0x83,
	MTI_EMV_TAG_DF_NAME = 0x84,
	MTI_EMV_TAG_ISSUER_SCRIPT_COMMAND = 0x86,
	MTI_EMV_TAG_APPLI_PRIORITY_INDICATOR = 0x87,
	MTI_EMV_TAG_SFI = 0x88,
	MTI_EMV_TAG_AUTHORISATION_CODE = 0x89,
	MTI_EMV_TAG_AUTHORISATION_RESPONSE_CODE = 0x8A,
	MTI_EMV_TAG_CDOL_1 = 0x8C,
	MTI_EMV_TAG_CDOL_2 = 0x8D,
	MTI_EMV_TAG_CVM_LIST_CARD = 0x8E,
	MTI_EMV_TAG_CA_PUBLIC_KEY_INDEX_CARD = 0x8F,
	MTI_EMV_TAG_ISSUER_PUBLIC_KEY_CERTIFICATE = 0x90,
	MTI_EMV_TAG_ISSUER_AUTHENTICATION_DATA = 0x91,
	MTI_EMV_TAG_ISSUER_PUBLIC_KEY_REMAINDER = 0x92,
	MTI_EMV_TAG_SIGNED_STATIC_APPLI_DATA = 0x93,
	MTI_EMV_TAG_AFL = 0x94,
	MTI_EMV_TAG_TVR = 0x95,
	MTI_EMV_TAG_TDOL = 0x97,
	MTI_EMV_TAG_TC_HASH_VALUE = 0x98,
	MTI_EMV_TAG_TRANSACTION_PIN_DATA = 0x99,
	MTI_EMV_TAG_TRANSACTION_DATE = 0x9A,
	MTI_EMV_TAG_TSI = 0x9B,
	MTI_EMV_TAG_TRANSACTION_TYPE = 0x9C,
	MTI_EMV_TAG_DDF_NAME = 0x9D,
	MTI_EMV_TAG_FCI_PROPRIETARY_TEMPLATE = 0xA5,
	MTI_EMV_TAG_CARDHOLDER_NAME = 0x5F20,
	MTI_EMV_TAG_APPLI_EXPIRATION_DATE = 0x5F24,
	MTI_EMV_TAG_APPLI_EFFECTIVE_DATE = 0x5F25,
	MTI_EMV_TAG_ISSUER_COUNTRY_CODE = 0x5F28,
	MTI_EMV_TAG_TRANSACTION_CURRENCY_CODE = 0x5F2A,
	MTI_EMV_TAG_LANGUAGE_PREFERENCE = 0x5F2D,
	MTI_EMV_TAG_SERVICE_CODE = 0x5F30,
	MTI_EMV_TAG_APPLI_PAN_SEQUENCE_NUMBER = 0x5F34,
	MTI_EMV_TAG_TRANSACTION_CURRENCY_EXPONENT = 0x5F36,
	MTI_EMV_TAG_ISSUER_URL = 0x5F50,
	MTI_EMV_TAG_IBAN = 0x5F53,
	MTI_EMV_TAG_BANK_IDENTIFIER_CODE = 0x5F54,
	MTI_EMV_TAG_ISSUER_COUNTRY_CODE_A2_FORMAT = 0x5F55,
	MTI_EMV_TAG_ISSUER_COUNTRY_CODE_A3_FORMAT = 0x5F56,
	MTI_EMV_TAG_ACCOUNT_TYPE = 0x5F57,
	MTI_EMV_TAG_ACQUIRER_IDENTIFIER = 0x9F01,
	MTI_EMV_TAG_AMOUNT_AUTH_NUM = 0x9F02,
	MTI_EMV_TAG_AMOUNT_OTHER_NUM = 0x9F03,
	MTI_EMV_TAG_AMOUNT_OTHER_BIN = 0x9F04,
	MTI_EMV_TAG_APPLI_DISCRET_DATA = 0x9F05,
	MTI_EMV_TAG_AID_TERMINAL = 0x9F06,
	MTI_EMV_TAG_APPLI_USAGE_CONTROL = 0x9F07,
	MTI_EMV_TAG_APPLI_VERSION_NUMBER_CARD = 0x9F08,
	MTI_EMV_TAG_APPLI_VERSION_NUMBER_TERM = 0x9F09,
	MTI_EMV_TAG_CARDHOLDER_NAME_EXTENDED = 0x9F0B,
	MTI_EMV_TAG_IAC_DEFAULT = 0x9F0D,
	MTI_EMV_TAG_IAC_DENIAL = 0x9F0E,
	MTI_EMV_TAG_IAC_ONLINE = 0x9F0F,
	MTI_EMV_TAG_ISSUER_APPLI_DATA = 0x9F10,
	MTI_EMV_TAG_ISSUER_CODE_TABLE_INDEX = 0x9F11,
	MTI_EMV_TAG_APPLI_PREFERRED_NAME = 0x9F12,
	MTI_EMV_TAG_LAST_ONLINE_ATC_REGISTER = 0x9F13,
	MTI_EMV_TAG_LOWER_CONSECUTIVE_OFFLINE_LIMIT = 0x9F14,
	MTI_EMV_TAG_MERCHANT_CATEGORY_CODE = 0x9F15,
	MTI_EMV_TAG_MERCHANT_IDENTIFIER = 0x9F16,
	MTI_EMV_TAG_PIN_TRY_COUNTER = 0x9F17,
	MTI_EMV_TAG_ISSUER_SCRIPT_IDENTIFIER = 0x9F18,
	MTI_EMV_TAG_TERMINAL_COUNTRY_CODE = 0x9F1A,
	MTI_EMV_TAG_TERMINAL_FLOOR_LIMIT = 0x9F1B,
	MTI_EMV_TAG_TERMINAL_IDENTIFICATION = 0x9F1C,
	MTI_EMV_TAG_TERMINAL_RISK_MANAGEMENT_DATA = 0x9F1D,
	MTI_EMV_TAG_IFD_SERIAL_NUMBER = 0x9F1E,
	MTI_EMV_TAG_TRACK_1_DISCRET_DATA = 0x9F1F,
	MTI_EMV_TAG_TRACK_2_DISCRET_DATA = 0x9F20,
	MTI_EMV_TAG_TRANSACTION_TIME = 0x9F21,
	MTI_EMV_TAG_CA_PUBLIC_KEY_INDEX_TERM = 0x9F22,
	MTI_EMV_TAG_UPPER_CONSECUTIVE_OFFLINE_LIMIT = 0x9F23,
	MTI_EMV_TAG_APPLICATION_CRYPTOGRAM = 0x9F26,
	MTI_EMV_TAG_CRYPTOGRAM_INFO_DATA = 0x9F27,
	MTI_EMV_TAG_ICC_PIN_ENCIPH_PK_CERTIFICATE = 0x9F2D,
	MTI_EMV_TAG_ICC_PIN_ENCIPH_PK_EXPONENT = 0x9F2E,
	MTI_EMV_TAG_ICC_PIN_ENCIPH_PK_REMAINDER = 0x9F2F,
	MTI_EMV_TAG_ISSUER_PK_EXPONENT = 0x9F32,
	MTI_EMV_TAG_TERMINAL_CAPABILITIES = 0x9F33,
	MTI_EMV_TAG_CVM_RESULTS = 0x9F34,
	MTI_EMV_TAG_TERMINAL_TYPE = 0x9F35,
	MTI_EMV_TAG_ATC = 0x9F36,
	MTI_EMV_TAG_UNPREDICTABLE_NUMBER = 0x9F37,
	MTI_EMV_TAG_PDOL = 0x9F38,
	MTI_EMV_TAG_POS_ENTRY_MODE = 0x9F39,
	MTI_EMV_TAG_AMOUNT_REF_CURRENCY = 0x9F3A,
	MTI_EMV_TAG_APPLI_REF_CURRENCY = 0x9F3B,
	MTI_EMV_TAG_TRANSACTION_REF_CURRENCY_CODE = 0x9F3C,
	MTI_EMV_TAG_TRANSACTION_REF_CURRENCY_EXPONENT = 0x9F3D,
	MTI_EMV_TAG_ADD_TERMINAL_CAPABILITIES = 0x9F40,
	MTI_EMV_TAG_TRANSACTION_SEQUENCE_COUNTER = 0x9F41,
	MTI_EMV_TAG_APPLI_CURRENCY_CODE = 0x9F42,
	MTI_EMV_TAG_APPLI_REF_CURRENCY_EXPONENT = 0x9F43,
	MTI_EMV_TAG_APPLI_CURRENCY_EXPONENT = 0x9F44,
	MTI_EMV_TAG_DATA_AUTHENTICATION_CODE = 0x9F45,
	MTI_EMV_TAG_ICC_PK_CERTIFICATE = 0x9F46,
	MTI_EMV_TAG_ICC_PK_EXPONENT = 0x9F47,
	MTI_EMV_TAG_ICC_PK_REMAINDER = 0x9F48,
	MTI_EMV_TAG_DDOL = 0x9F49,
	MTI_EMV_TAG_SDA_TAG_LIST = 0x9F4A,
	MTI_EMV_TAG_SIGNED_DYNAMIC_APPLI_DATA = 0x9F4B,
	MTI_EMV_TAG_ICC_DYNAMIC_NUMBER = 0x9F4C,
	MTI_EMV_TAG_LOG_ENTRY = 0x9F4D,
	MTI_EMV_TAG_MERCHANT_NAME_AND_LOCATION = 0x9F4E,
	MTI_EMV_TAG_LOG_FORMAT = 0x9F4F,
	MTI_EMV_TAG_TRANSACTION_CATEGORY_CODE = 0x9F53,
	MTI_EMV_TAG_TAC_DEFAULT = 0x9F82,
	MTI_EMV_TAG_TAC_DENIAL = 0x9F83,
	MTI_EMV_TAG_TAC_ONLINE = 0x9F84,
	MTI_EMV_TAG_TARGET_PERC_RAND_SEL = 0x9F85,
	MTI_EMV_TAG_MAX_TARGET_PERC_BIASED_RAND_SEL = 0x9F86,
	MTI_EMV_TAG_THRESHOLD_VALUE_BIASED_RAND_SEL = 0x9F87,
	MTI_EMV_TAG_DEFAULT_DDOL = 0x9F89,
	MTI_EMV_TAG_TTQ = 0x9F66,
	MTI_EMV_TAG_FCI_ISSUER_DISCRET_DATA = 0xBF0C,

	//RF EMV
		//PAYWAVE
	MTI_RFEMV_TAG_PAYWAVE_TRX_LIMIT = 0xDF00,
	MTI_RFEMV_TAG_PAYWAVE_CVM_LIMIT = 0xDF01,
	MTI_RFEMV_TAG_PAYWAVE_FLOOR_LIMIT = 0xDF02,

		//PAYPASS
	MTI_RFEMV_TAG_PAYPASS_DEFAULT_UDOL = 0xEF01,
	MTI_RFEMV_TAG_PAYPASS_FLOOR_LIMIT = 0xEF02,
	MTI_RFEMV_TAG_PAYPASS_TRX_NODCV_LIMIT = 0xEF03,
	MTI_RFEMV_TAG_PAYPASS_TRX_DCV_LIMIT = 0xEF04,
	MTI_RFEMV_TAG_PAYPASS_CVM_REQ_LIMIT = 0xEF05,
	MTI_RFEMV_TAG_PAYPASS_SEC_CAPABILITY = 0xEF06,
	MTI_RFEMV_TAG_PAYPASS_TAC_DEFAULT = 0xEF07,
	MTI_RFEMV_TAG_PAYPASS_TAC_DENIAL = 0xEF08,
	MTI_RFEMV_TAG_PAYPASS_TAC_ONLINE = 0xEF09,

	//JSPEEDY //@@WAY JCB Cless
	MTI_RFEMV_TAG_JSPEEDY_TRX_LIMIT = 0xFF00,
	MTI_RFEMV_TAG_JSPEEDY_CVM_LIMIT = 0xFF01,
	MTI_RFEMV_TAG_JSPEEDY_FLOOR_LIMIT = 0xFF03

};

enum eRFEmvDefaultParamKey {
	MTI_RFEMV_KEY_AMOUNT = 1000,
};

typedef struct _tEmvParammInfo {
	INT (*FuncUICallback)(INT, VOID *, VOID *);
	INT (*FuncInputAIDListCallback)(tMtiMap *);
	INT (*FuncInputAIDParamCallback)(tMtiMap *);
	INT (*FuncInputGlobalParamCallback)(tMtiMap *);
	INT (*FuncInputCAPKCallback)(tMtiMap *);
	INT iEmvStep;
	INT iEmvCtrlChannel;
	tMtiMap *tpMainProcMap;
	tMtiMap *tpSubProcMap;
	tMtiMap tEmvTagMap;
	INT iTranType;
} tEmvParamInfo;

#ifdef __cplusplus
extern "C" {
#endif

/**
 *
 * @return
 */
tEmvParamInfo *mtiEmvInitialize();

/**
 *
 * @return
 */
tEmvParamInfo *mtiGetEmvParmInfo();

/**
 *
 * @param tpEmvParamInfo
 * @return
 */
INT mtiEmvSession(tEmvParamInfo *tpEmvParamInfo);

/**
 *
 * @param bDoClear
 * @return
 */
INT mtiEmvSetParam(INT bDoClear);

/**
 *
 * @param tpEmvParamInfo
 * @return
 */
VOID mtiEmvFinalize(tEmvParamInfo *tpEmvParamInfo);

/**
 *
 * @return
 */
tEmvParamInfo *mtiRfEmvInitialize();

/**
 *
 * @return
 */
tEmvParamInfo *mtiGetRfEmvParmInfo();

/**
 *
 * @param tpEmvParamInfo
 * @return
 */
INT mtiRfEmvSession(tEmvParamInfo *tpEmvParamInfo);

/**
 *
 * @param bDoClear
 * @return
 */
INT mtiRfEmvSetParam(BOOL bDoClear);

/**
 *
 * @param tpEmvParamInfo
 * @return
 */
VOID mtiRfEmvFinalize(tEmvParamInfo *tpEmvParamInfo);

#ifdef __cplusplus
}
#endif

#endif

